workshop10/blog/urls.py
from django.urls import path
from blog.views import home_view, post_detail_view, post_rate_view, post_create_view

app_name = 'blog'
urlpatterns = [
    path('', home_view, name='home'),
    path('posts/create/', post_create_view, name='post-create'),
    path('post/<int:pk>/', post_detail_view, name='post-detail'),
    path('post/<int:pk>/like/', post_rate_view, name='post-rate')
]

workshop10/workshop10/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workshop10/blog/models.py
import datetime
from distutils.command.upload import upload
from statistics import mode
from django.db import models

from users.models import User
from django.shortcuts import reverse


# Create your models here.
"""
Post Model
    - author            (User reference)
    - name              (string)
    - text              (string)
    / - image             (File) /

    - create date       (datetime)
    - edit date         (datetime)


Comment Model
    - author            (User reference)
    - post              (Post reference)
    - text              (string)

    - create date       (datetime)

Rating Model
    - user              (User reference)
    - post              (Post reference)
    - positive          (boolean)

"""

class Post(models.Model):
    # ORM - object relational mapper
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='posts/', null=True, blank=True)

    text = models.TextField()

    create_date: datetime.datetime = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)

    def get_create_date(self) -> str:
        return self.create_date.strftime('%d %b').upper()
    
    def get_likes(self) -> int:
        return self.rating_set.filter(is_positive=True).count()
    
    def get_dislikes(self) -> int:
        return self.rating_set.filter(is_positive=False).count()
    
    def get_absolute_url(self):
        return reverse("blog:post-detail", kwargs={"pk": self.pk})

    def rate_link(self):
        return reverse("blog:post-rate", kwargs={"pk": self.pk})


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    text = models.TextField()

    create_date = models.DateTimeField(auto_now_add=True)


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    is_positive = models.BooleanField(default=True)

    class Meta:
        unique_together = ('user', 'post')

workshop10/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

workshop10/blog/forms.py
from django import forms
from blog.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        fields = ['name', 'text', 'image']
    
    def save(self, commit: bool = ..., user = None):
        post = super().save(commit=False)

        if commit:
            post.author = user
            post.save()
        return post

workshop10/blog/views.py
import django
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from blog.models import Post, Rating
from django.http import HttpResponseBadRequest
from django.views.generic import CreateView

from blog.forms import PostForm


# Create your views here.
"""
Post Create View                    - render post form on page and create post object in database
Post Edit View                      - render post form (pre filled) and update post object in database
Post Delete View                    - render button to ask user if they're sure to 
                                    delete and after that delete post from db
Post List View (Home View)          - Where all posts are rendered with their recent 1-2 comments
Post Detail View                    - render all details about post with their comments
"""

def home_view(request):
    posts = Post.objects.all()
    post_create_form = PostForm()

    return render(request, 'home.html', context={
        'posts': posts,
        'form': post_create_form
    })


def post_create_view(request):
    if request.method == 'GET':
        return redirect('blog:home')

    form = PostForm(request.POST, request.FILES)

    if not form.is_valid():
        return redirect('blog:home')

    form.save(user=request.user)
    return redirect('blog:home')


def post_detail_view(request, pk: int):
    post = get_object_or_404(Post, pk=pk)

    return render(request, 'post_details.html', {
        'post': post
    })


@login_required
def post_rate_view(request, pk: int):
    # print(request.GET)
    # if not request.user.is_authenticated:
    #     pass

    if request.method == 'GET':
        # User tried to like with get request
        return redirect('blog:home')

    try:
        is_positive = bool(int(request.POST['is_positive']))
    except ValueError:
        # User tried to send invalid data
        return redirect('blog:home')

    
    post = get_object_or_404(Post, pk=pk)
    try:
        rating, created = Rating.objects.get_or_create(post=post, user=request.user, is_positive=is_positive)
        if not created:
            # user already has liked this post
            return redirect('blog:home')
    except django.db.utils.IntegrityError:
        rating = Rating.objects.get(post=post, user=request.user)
        rating.is_positive = not rating.is_positive
        rating.save()

    return redirect('blog:home')

workshop10/users/views.py
from django.shortcuts import render

# Create your views here.

workshop10/templates/__home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Blog Post</h1>

    {% for post in posts %}
        <h4>{{ post.name }}</h4>

        <p>{{ post.author }}</p>
        <p>{{ post.create_date }}</p>
    {% endfor %}
</body>
</html>

workshop10/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
   <!-- header section end -->
   <form method='POST' action="{% url 'blog:post-create' %}" style='text-align: center' enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="get_bt">Post</button>
   </form>
   <!-- barber section start -->
   <div class="barber_section layout_padding">

      <div class="container">
         {% for post in posts %}
         <div class="braber_taital_main">
            <div class="row">
               <div class="col-lg-6">
                  <div class="barber_bg_main">
                     <h1 class="barber_taital"><a href="{{ post.get_absolute_url }}">{{ post.name }}<a/></h1>
                     <p class="barber_text">{{ post.text }}</p>
                     <div class="blogr_main">
                        <div class="blogr_left">
                           <p class="post_text">Post By : {{ post.author }}</p>
                        </div>
                        <div class="blogr_right">
                           <div class="comment_text">
                              <ul>
                                 <li>
                                    <form action="{{ post.rate_link }}" method="POST">
                                       {% csrf_token %}
                                       <input name='is_positive' value='1' hidden/>
                                       <button><span class="">{{ post.get_likes }} <i class="fa fa-thumbs-up"></i></span></button>
                                    </form>
                                 </li>
                                 <li>
                                    <form action="{{ post.rate_link }}" method="POST">
                                       {% csrf_token %}
                                       <input name='is_positive' value='0' hidden/>
                                       <button><span class="">{{ post.get_dislikes }} <i class="fa fa-thumbs-down"></i></i></span></button>
                                    </form>
                                 </li>
                                 <li><a href="#">{{ post.comment_set.count }}<span class="padding_10"><i class="fa fa-comment"></i></span></a></li>
                                 <li><a href="#">Share<span class="padding_10"><i class="fa fa-share-alt" aria-hidden="true"></i></span></a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="col-lg-6">
                  <div class="fashion_img">
                     {% if post.image %}
                     <img src="{{ post.image.url }}" class="fashion_img">
                     {% else %}
                     <h3>No Image<h3/>
                     {% endif %}
                     <div class="read_bt"><a href="#">{{ post.get_create_date }}</a></div>
                  </div>
               </div>
            </div>
         </div>
         {% endfor %}
      </div>
   </div>
{% endblock content %}

workshop10/templates/post_details.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ post.name }}</h1>

    {% for comment in post.comment_set.all %}
    <div style='border: 1px solid black'>
        <p>{{ comment.create_date }} &mdash; {{ comment.author }}</p>
        <p>
            {{ comment.text }}
        </p>
    </div>
    {% endfor %}
{% endblock content %}